name: social_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.9.0
  flutter_svg: ^2.0.4
  image_picker: ^0.8.7+1
  uuid: ^3.0.6
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0
  intl_phone_field: ^3.1.0
  firebase_auth: ^4.4.0
  get_storage: ^2.1.1
  flutter_staggered_grid_view: ^0.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
