// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbQ308UBtx54ph97NC_Yip8HGaWsAO9io',
    appId: '1:554254052407:web:ba0c0e6ffdd96613e063b2',
    messagingSenderId: '554254052407',
    projectId: 'newsocial-bef86',
    authDomain: 'newsocial-bef86.firebaseapp.com',
    storageBucket: 'newsocial-bef86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI2yP8fQPg_5uH2wf9qAiKJiNRplZewA0',
    appId: '1:554254052407:android:3bc8ef263180b90ae063b2',
    messagingSenderId: '554254052407',
    projectId: 'newsocial-bef86',
    storageBucket: 'newsocial-bef86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4idLv8E6dJoJjzR_jvP5yeQLxrv40_M',
    appId: '1:554254052407:ios:0d388653d8a03834e063b2',
    messagingSenderId: '554254052407',
    projectId: 'newsocial-bef86',
    storageBucket: 'newsocial-bef86.appspot.com',
    iosClientId: '554254052407-e7qbkg7hpi7qrbi85s571o65c7nanmln.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4idLv8E6dJoJjzR_jvP5yeQLxrv40_M',
    appId: '1:554254052407:ios:0d388653d8a03834e063b2',
    messagingSenderId: '554254052407',
    projectId: 'newsocial-bef86',
    storageBucket: 'newsocial-bef86.appspot.com',
    iosClientId: '554254052407-e7qbkg7hpi7qrbi85s571o65c7nanmln.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
