// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCewIO4w20slk9vqRVRGkWiBaCEmDRAMac',
    appId: '1:966329376483:web:999b351f6f93623a48afd6',
    messagingSenderId: '966329376483',
    projectId: 'socialapp-1fbd2',
    authDomain: 'socialapp-1fbd2.firebaseapp.com',
    storageBucket: 'socialapp-1fbd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCkHC58XbLwuysB4WVJnB0s41-MPye960',
    appId: '1:966329376483:android:4ba5268c897f9d1f48afd6',
    messagingSenderId: '966329376483',
    projectId: 'socialapp-1fbd2',
    storageBucket: 'socialapp-1fbd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoj24Se6GSDLPnp3-_nJWDVEcKCs0Ziao',
    appId: '1:966329376483:ios:9bfbd66e2620b47948afd6',
    messagingSenderId: '966329376483',
    projectId: 'socialapp-1fbd2',
    storageBucket: 'socialapp-1fbd2.appspot.com',
    iosClientId: '966329376483-qv84gfb3lpt8gh4prita0h8urqvcdico.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoj24Se6GSDLPnp3-_nJWDVEcKCs0Ziao',
    appId: '1:966329376483:ios:9bfbd66e2620b47948afd6',
    messagingSenderId: '966329376483',
    projectId: 'socialapp-1fbd2',
    storageBucket: 'socialapp-1fbd2.appspot.com',
    iosClientId: '966329376483-qv84gfb3lpt8gh4prita0h8urqvcdico.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
